import { LuCheck, LuDice5, LuSearch, LuType } from "react-icons/lu";
import type { AutomationNodeCatalogItem } from "../node-catalog";

export const EXTRACTION_CATALOG: AutomationNodeCatalogItem[] = [
  {
    type: "getText",
    group: "data",
    labelKey: "automation.nodes.getText.label",
    descriptionKey: "automation.nodes.getText.description",
    documentKey: "automation.nodes.getText.document",
    icon: LuType,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: "#email, .title, [data-id]",
        labelKey: "automation.nodes.getText.params.selector",
        helpKey: "automation.nodes.getText.help.selector",
      },
      {
        key: "saveToVar",
        kind: "string",
        required: true,
        placeholder: "textContent",
        labelKey: "automation.nodes.getText.params.saveToVar",
        helpKey: "automation.nodes.getText.help.saveToVar",
      },
      {
        key: "timeout",
        kind: "number",
        required: false,
        placeholder: "30000",
        labelKey: "automation.nodes.getText.params.timeout",
      },
    ],
    defaults: {
      timeout: 30000,
    },
  },
  {
    type: "getAttributeValue",
    group: "data",
    labelKey: "automation.nodes.getAttributeValue.label",
    descriptionKey: "automation.nodes.getAttributeValue.description",
    documentKey: "automation.nodes.getAttributeValue.document",
    icon: LuSearch,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: "a.link, img.logo",
        labelKey: "automation.nodes.getAttributeValue.params.selector",
      },
      {
        key: "attribute",
        kind: "string",
        required: true,
        placeholder: "href, src, data-id",
        labelKey: "automation.nodes.getAttributeValue.params.attribute",
      },
      {
        key: "saveToVar",
        kind: "string",
        required: true,
        placeholder: "attrValue",
        labelKey: "automation.nodes.getAttributeValue.params.saveToVar",
      },
      {
        key: "timeout",
        kind: "number",
        required: false,
        placeholder: "30000",
        labelKey: "automation.nodes.getAttributeValue.params.timeout",
      },
    ],
    defaults: {
      timeout: 30000,
    },
  },
  {
    type: "getValue",
    group: "data",
    labelKey: "automation.nodes.getValue.label",
    descriptionKey: "automation.nodes.getValue.description",
    documentKey: "automation.nodes.getValue.document",
    icon: LuType,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: "input#email, textarea.comment, select.country",
        labelKey: "automation.nodes.getValue.params.selector",
      },
      {
        key: "saveToVar",
        kind: "string",
        required: true,
        placeholder: "inputValue",
        labelKey: "automation.nodes.getValue.params.saveToVar",
      },
      {
        key: "timeout",
        kind: "number",
        required: false,
        placeholder: "30000",
        labelKey: "automation.nodes.getValue.params.timeout",
      },
    ],
    defaults: {
      timeout: 30000,
    },
  },
  {
    type: "elementExists",
    group: "data",
    labelKey: "automation.nodes.elementExists.label",
    descriptionKey: "automation.nodes.elementExists.description",
    documentKey: "automation.nodes.elementExists.document",
    icon: LuCheck,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: ".error-message, #loading-spinner",
        labelKey: "automation.nodes.elementExists.params.selector",
      },
      {
        key: "visibility",
        kind: "enum",
        required: false,
        placeholder: "visible",
        labelKey: "automation.nodes.elementExists.params.visibility",
        options: [
          {
            value: "visible",
            labelKey: "automation.nodes.elementExists.options.visible",
          },
          {
            value: "hidden",
            labelKey: "automation.nodes.elementExists.options.hidden",
          },
          {
            value: "any",
            labelKey: "automation.nodes.elementExists.options.any",
          },
        ],
      },
      {
        key: "timeout",
        kind: "number",
        required: false,
        placeholder: "30000",
        labelKey: "automation.nodes.elementExists.params.timeout",
      },
    ],
    defaults: {
      visibility: "visible",
      timeout: 30000,
    },
  },
  {
    type: "extractionInText",
    group: "data",
    labelKey: "automation.nodes.extractionInText.label",
    descriptionKey: "automation.nodes.extractionInText.description",
    documentKey: "automation.nodes.extractionInText.document",
    icon: LuSearch,
    params: [
      {
        key: "text",
        kind: "string",
        required: true,
        multiline: true,
        supportsExpression: true,
        placeholder: "Some text {{variable}} content",
        labelKey: "automation.nodes.extractionInText.params.text",
      },
      {
        key: "regex",
        kind: "string",
        required: true,
        placeholder: "email: ([\\w.]+@[\\w.]+)",
        labelKey: "automation.nodes.extractionInText.params.regex",
      },
      {
        key: "saveToVar",
        kind: "string",
        required: true,
        placeholder: "extractedValue",
        labelKey: "automation.nodes.extractionInText.params.saveToVar",
      },
      {
        key: "flags",
        kind: "string",
        required: false,
        placeholder: "i, g, m",
        labelKey: "automation.nodes.extractionInText.params.flags",
      },
    ],
    defaults: {},
  },
  {
    type: "random",
    group: "data",
    labelKey: "automation.nodes.random.label",
    descriptionKey: "automation.nodes.random.description",
    documentKey: "automation.nodes.random.document",
    icon: LuDice5,
    params: [
      {
        key: "type",
        kind: "enum",
        required: true,
        labelKey: "automation.nodes.random.params.type",
        options: [
          { value: "email", labelKey: "automation.nodes.random.options.email" },
          {
            value: "fullName",
            labelKey: "automation.nodes.random.options.fullName",
          },
          {
            value: "randomLetters",
            labelKey: "automation.nodes.random.options.randomLetters",
          },
          {
            value: "password",
            labelKey: "automation.nodes.random.options.password",
          },
          {
            value: "firstName",
            labelKey: "automation.nodes.random.options.firstName",
          },
          {
            value: "lastName",
            labelKey: "automation.nodes.random.options.lastName",
          },
          {
            value: "number",
            labelKey: "automation.nodes.random.options.number",
          },
        ],
      },
      {
        key: "saveToVar",
        kind: "string",
        required: true,
        placeholder: "randomValue",
        labelKey: "automation.nodes.random.params.saveToVar",
      },
      {
        key: "domain",
        kind: "string",
        required: false,
        placeholder: "example.com",
        labelKey: "automation.nodes.random.params.domain",
        helpKey: "automation.nodes.random.help.domain",
      },
      {
        key: "quantity",
        kind: "number",
        required: false,
        placeholder: "10",
        labelKey: "automation.nodes.random.params.quantity",
      },
      {
        key: "length",
        kind: "number",
        required: false,
        placeholder: "12",
        labelKey: "automation.nodes.random.params.length",
      },
      {
        key: "min",
        kind: "number",
        required: false,
        placeholder: "0",
        labelKey: "automation.nodes.random.params.min",
      },
      {
        key: "max",
        kind: "number",
        required: false,
        placeholder: "100",
        labelKey: "automation.nodes.random.params.max",
      },
    ],
    defaults: {},
  },
];
