import {
  LuDownload,
  LuEraser,
  LuKeyboard,
  LuMousePointerClick,
  LuMove,
  LuPenTool,
  LuPointer,
  LuScroll,
  LuUpload,
} from "react-icons/lu";
import type { AutomationNodeCatalogItem, ParamOption } from "../node-catalog";

const BUTTON_OPTIONS: ParamOption[] = [
  { value: "left" },
  { value: "right" },
  { value: "middle" },
];

export const INTERACTION_CATALOG: AutomationNodeCatalogItem[] = [
  {
    type: "click",
    group: "interaction",
    labelKey: "automation.nodes.click.label",
    descriptionKey: "automation.nodes.click.description",
    documentKey: "automation.nodes.click.document",
    icon: LuMousePointerClick,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: "button[type=submit]",
        supportsExpression: true,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
      {
        key: "button",
        kind: "enum",
        placeholder: "left",
        options: BUTTON_OPTIONS,
      },
      { key: "clickCount", kind: "number", placeholder: "1" },
    ],
    defaults: { selector: "button" },
  },
  {
    type: "hover",
    group: "interaction",
    labelKey: "automation.nodes.hover.label",
    descriptionKey: "automation.nodes.hover.description",
    documentKey: "automation.nodes.hover.document",
    icon: LuPointer,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: ".menu-item",
        supportsExpression: true,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
    ],
    defaults: { selector: ".menu-item" },
  },
  {
    type: "scroll",
    group: "navigator", // Group navigator matching catalog
    labelKey: "automation.nodes.scroll.label",
    descriptionKey: "automation.nodes.scroll.description",
    documentKey: "automation.nodes.scroll.document",
    icon: LuScroll,
    params: [
      {
        key: "selector",
        kind: "string",
        placeholder: "body",
        supportsExpression: true,
      },
      { key: "x", kind: "number", placeholder: "0" },
      { key: "y", kind: "number", placeholder: "600" },
    ],
    defaults: { x: 0, y: 600 },
  },
  {
    type: "dragAndDrop",
    group: "interaction",
    labelKey: "automation.nodes.dragAndDrop.label",
    descriptionKey: "automation.nodes.dragAndDrop.description",
    documentKey: "automation.nodes.dragAndDrop.document",
    icon: LuMove,
    params: [
      {
        key: "sourceSelector",
        kind: "string",
        required: true,
        placeholder: "#drag-source",
        supportsExpression: true,
      },
      {
        key: "targetSelector",
        kind: "string",
        required: true,
        placeholder: "#drop-target",
        supportsExpression: true,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
    ],
    defaults: { sourceSelector: "", targetSelector: "" },
  },
  {
    type: "clickDown",
    group: "interaction",
    labelKey: "automation.nodes.clickDown.label",
    descriptionKey: "automation.nodes.clickDown.description",
    documentKey: "automation.nodes.clickDown.document",
    icon: LuDownload,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: ".canvas",
        supportsExpression: true,
      },
      {
        key: "button",
        kind: "enum",
        placeholder: "left",
        options: BUTTON_OPTIONS,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
    ],
    defaults: { selector: ".canvas" },
  },
  {
    type: "clickUp",
    group: "interaction",
    labelKey: "automation.nodes.clickUp.label",
    descriptionKey: "automation.nodes.clickUp.description",
    documentKey: "automation.nodes.clickUp.document",
    icon: LuUpload,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: ".canvas",
        supportsExpression: true,
      },
      {
        key: "button",
        kind: "enum",
        placeholder: "left",
        options: BUTTON_OPTIONS,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
    ],
    defaults: { selector: ".canvas" },
  },
  {
    type: "type",
    group: "interaction",
    labelKey: "automation.nodes.type.label",
    descriptionKey: "automation.nodes.type.description",
    documentKey: "automation.nodes.type.document",
    icon: LuKeyboard,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: "input[name=email]",
        supportsExpression: true,
      },
      {
        key: "text",
        kind: "string",
        required: true,
        placeholder: "{{EMAIL}}",
        supportsExpression: true,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
      { key: "delay", kind: "number", placeholder: "25" },
    ],
    defaults: { selector: "input", text: "" },
  },
  {
    type: "pressKey",
    group: "interaction",
    labelKey: "automation.nodes.pressKey.label",
    descriptionKey: "automation.nodes.pressKey.description",
    documentKey: "automation.nodes.pressKey.document",
    icon: LuPenTool,
    params: [
      {
        key: "key",
        kind: "string",
        required: true,
        placeholder: "Enter",
      },
      {
        key: "selector",
        kind: "string",
        required: false,
        placeholder: "body",
        supportsExpression: true,
      },
    ],
    defaults: { key: "Enter" },
  },
  {
    type: "clearInput",
    group: "interaction",
    labelKey: "automation.nodes.clearInput.label",
    descriptionKey: "automation.nodes.clearInput.description",
    documentKey: "automation.nodes.clearInput.document",
    icon: LuEraser,
    params: [
      {
        key: "selector",
        kind: "string",
        required: true,
        placeholder: "input[name=username]",
        supportsExpression: true,
      },
      { key: "timeout", kind: "number", placeholder: "30000" },
    ],
    defaults: { selector: "input" },
  },
];
